### PR TITLE
Fixes and improvements for spells filter & some misc UI changes 

### LINKED ISSUE #23: Spell filtering by class doesn't work
The button does absolutely nothing

### PR DESCRIPTION
**Pull request by FlyinPancake**

### CODE REVIEW

File: android-app/app/src/main/java/com/nimtome/app/ui/components/SpellFilterComponent.kt [hunk 1]
```diff
@@ -57,12 +52,20 @@ fun SpellFilterComponent(
...
             }
 
-            Text("Level " + spellFilter.levelFilter.toInt())
+            Text("Level ${spellFilter.levelFilter.toRange().lower.roundToInt()} - ${spellFilter.levelFilter.toRange().upper.roundToInt()}")
         }
-        Slider(
-            value = spellFilter.levelFilter / MAX_SPELL_LEVEL,
-            onValueChange = { onSpellFilterChanged(spellFilter.copy(levelFilter = it * MAX_SPELL_LEVEL)) },
-            enabled = spellFilter.levelFilterEnabled
+//        Slider(
```
Comment (Dewyer) [inline android-app/app/src/main/java/com/nimtome/app/ui/components/SpellFilterComponent.kt]: Please remove this commented out code

**Review by Dewyer — APPROVED** [review]
